README.md
components/index.ts
components/select/select.ts
demo/app/app.module.ts
demo/app/pages/getting-started/getting-started.page.html
demo/app/pages/getting-started/getting-started.page.ts
demo/test.ts
ng2-semantic-ui.ts
package.json

* Added support for individually loading components
* Fixed compile error when using rc.6

v0.3.2 into Master

---

.gitattributes
README.md
demo/app/pages/getting-started/getting-started.page.html
ng2-semantic-ui.ts
package.json

* Full support for Angular 2 rc.6
* Fix bug when loading with SystemJS

v0.3.3 into Master

---

package.json

* Updated internal dependencies to rc.6 (fixes #14)

v0.3.4 into Master

---

components/search/search.ts
components/select/multi-select.ts
components/select/select.ts
components/transition/transition.ts
package.json

Hi, 
For this to run on my system I had to 
* update some dependencies
* fix the typescript errors:
```
ng2-semantic-ui/components/search/search.ts(42,24): error TS7006: Parameter 'isOpen' implicitly has an 'any' type.
ng2-semantic-ui/components/select/multi-select.ts(161,24): error TS7006: Parameter 'isOpen' implicitly has an 'any' type.
ng2-semantic-ui/components/select/multi-select.ts(261,46): error TS7006: Parameter 'o' implicitly has an 'any' type.
ng2-semantic-ui/components/select/select.ts(157,24): error TS7006: Parameter 'isOpen' implicitly has an 'any' type.
ng2-semantic-ui/components/select/select.ts(235,57): error TS7006: Parameter 'o' implicitly has an 'any' type.
ng2-semantic-ui/components/transition/transition.ts(45,5): error TS7008: Member '_isVisible' implicitly has an …
```

Build and compile fixes

---

components/message/message.ts
components/select/multi-select.ts
components/select/select.ts
demo/app/pages/select/select.page.ts
package.json

* Bugfixes for select components using NgModel
* Fixed multi select docs
* Typescript compilation fixes (thanks to @karlhiramoto)

v0.4.6 into master

---

components/search/search.service.ts
components/search/search.ts

Improvements in Search-Component:
replaces stringcomparison with regular expression
adds option to highlight match in searchresults

Improvements in Search-Component

---

.gitignore
README.md
components/util/positioning.service.ts
demo/src/app/app.component.html
demo/src/app/pages/getting-started/getting-started.page.html
demo/src/app/pages/getting-started/getting-started.page.ts
package.json
rollup.config.js
tsconfig.json

* Fixed bundle build for SystemJS compatibility (closes #49)

v0.6.1 into master

---

components/checkbox/checkbox.ts
components/checkbox/radiobutton.ts
components/message/message.ts
components/progress/progress.ts
components/rating/rating.ts
components/select/multi-select.ts
components/select/select-base.ts
components/select/select.ts
demo/src/app/components/codeblock/codeblock.component.ts
demo/src/app/components/example/example.component.ts
demo/src/app/pages/accordion/accordion.page.ts
demo/src/app/pages/checkbox/checkbox.page.ts
demo/src/app/pages/collapse/collapse.page.ts
demo/src/app/pages/dimmer/dimmer.page.ts
demo/src/app/pages/dropdown/dropdown.page.ts
demo/src/app/pages/message/message.page.ts
demo/src/app/pages/popup/popup.page.ts
demo/src/app/pages/progress/progress.page.ts
demo/src/app/pages/rating/rating.page.ts
demo/src/app/pages/search/search.page.ts
demo/src/app/pages/select/select.page.ts
demo/src/app/pages/sidebar/sidebar.page.ts
demo/src/app/pages/tabs/tabs.page.ts
demo/src/app/pages/transition/transition.page.ts
package.json

* Fixed `ngModel` item not being highlighted in select when using reactive forms (closes #52)
* Fixed AoT build when using Angular CLI (closes #53)

v0.6.2 into master

---

.gitignore
components/popup/popup.ts
components/util/positioning.service.ts
demo/src/app/components/sidebar/sidebar.component.html
demo/src/app/pages/transition/transition.page.ts
package.json
tsconfig.json
typings/popper.override.ts

* Fixed Popper.js related compilation error (closes #60, #62)
* Updated documentation for manual popup triggering (closes #56)
* Updated docs to address confusing mention of AngularJS (closes #58)

v0.6.3 into Master

---

components/dropdown/dropdown-menu.ts
components/select/multi-select-label.ts
components/transition/transition-controller.ts
components/transition/transition.ts

Fix problem with dropdown blinking when using ChangeDetectionStratege.OnPush. This should fix #59.

Fix problem with dropdown blinking when using ChangeDetectionStrategy.OnPush

---

README.md
components/collapse/collapse.ts
components/modal/modal-config.ts
components/modal/modal.service.ts
components/modal/modal.ts
components/popup/popup.ts
components/search/search.service.ts
components/select/multi-select.ts
components/select/select.ts
components/util/positioning.service.ts
demo/src/app/pages/getting-started/getting-started.page.html
demo/src/app/pages/modal/modal.page.ts
demo/src/app/pages/popup/popup.page.ts
demo/src/app/pages/search/search.page.html
demo/src/app/pages/search/search.page.ts
demo/src/app/pages/select/select.page.ts
demo/src/index.html
package.json

* Modal
- Added automatic & manual scrolling functionality (see `mustScroll` in the docs, closes #87)
- Fixed transition not working when opening (closes #86)
* Search & Select
- Expanded option lookup to support returning results immediately (closes #85)
* Popup
- Fixed arrows not pointing in the right direction when popups are auto-repositioned (closes #83)
* Angular
- Added `typescript^2.3.0` as a peer dependency to avoid AOT issue introduced by having a lower version (closes #88)

v0.8.1 into master

---

components/search/search.ts
demo/src/app/app.module.ts
demo/src/app/modals/alert.modal.ts
demo/src/app/modals/confirm.modal.ts
demo/src/app/modals/demo-modals.module.ts
demo/src/app/pages/collapse/collapse.page.html
demo/src/app/pages/collapse/collapse.page.ts
demo/src/app/pages/modal/modal.page.ts
demo/src/app/pages/search/search.page.ts
demo/src/app/pages/tabs/tabs.page.ts

fix(search): search now closes correctly after selecting a result

---

components/search/search.ts
components/select/multi-select.ts
components/select/select-base.ts
components/select/select.ts
demo/src/app/pages/message/message.page.ts
demo/src/app/pages/search/search.page.ts
demo/src/app/pages/select/select.page.ts

feat: extended search & select with transition options

---

components/progress/progress.ts

fix(progress): Progress now honours manual addition of success class

---

components/progress/progress.ts

fix(progress): Attached bars now show proper border radius

---

components/search/search.ts
demo/src/app/pages/search/search.page.ts

feat(search): added maxResults option

---

components/dropdown/dropdown-menu.ts
components/dropdown/dropdown.ts
components/select/multi-select-label.ts
components/select/select-base.ts
components/select/select-option.ts
components/util/util.ts
demo/src/index.html
demo/src/polyfills.ts

fix: Fixed error in Safari <=9 (and iOS) due to assigning to readonly property

---

components/dropdown/dropdown.ts

fix(dropdown): Toggle buttons on page now work correctly

---

components/select/multi-select.ts
components/select/select-base.ts
components/select/select.ts

fix(select): Selects now close regardless of searchability when caret clicked

---

components/modal/modal.service.ts

fix(modal): Polyfilled element remove for IE11

---

src/modal/modal.service.ts
src/modal/modal.ts
src/util/util.ts

Moved DOM manipulation into modal component, so it happens for manual (automatic) modals as well.
Closes #126

fix(modal): Automatic modals now scroll & position correctly

---

README.md
demo/src/app/pages/pagination/pagination.page.ts
src/pagination/pagination.ts

feat(pagination): Minor additions

---

demo/src/app/pages/modal/modal.page.ts
src/modal/modal-config.ts
src/modal/modal.ts

Simple enhancement to allow inverted modals.

feat(modal): Allow inverted modals

---

demo/src/app/pages/behaviors/localization/localization.page.ts
src/behaviors/localization/locales/index.ts
src/behaviors/localization/locales/it-IT.ts
src/behaviors/localization/locales/it.ts

feat(localization): Italian localization

---

demo/src/app/modals/alert.modal.ts
demo/src/app/modals/confirm.modal.ts
demo/src/app/pages/behaviors/localization/localization.page.ts
demo/src/app/pages/modules/datepicker/datepicker.page.ts
demo/src/app/pages/modules/modal/modal.page.html
demo/src/app/pages/modules/modal/modal.page.ts
demo/src/app/pages/modules/popup/popup.page.html
demo/src/app/pages/modules/popup/popup.page.ts
demo/src/app/pages/modules/transition/transition.page.ts
src/modules/modal/components/modal.ts
src/modules/popup/components/popup.ts

feat: Added autofocus support to modal & popup

---

demo/src/app/pages/demo-pages.module.ts
demo/src/app/pages/development/test/test.page.html
demo/src/app/pages/development/test/test.page.ts
scripts/bundle.js
src/behaviors/localization/services/localization.service.ts
src/modules/accordion/components/accordion-panel.ts
src/modules/accordion/components/accordion.ts
src/modules/checkbox/components/checkbox.ts
src/modules/checkbox/components/radiobutton.ts
src/modules/datepicker/directives/input.directive.ts
src/modules/dropdown/directives/dropdown.ts
src/modules/search/components/search.ts
src/modules/select/classes/select-base.ts
src/modules/select/components/multi-select.ts
src/modules/select/components/select.ts

misc: Various fixes

---

src/modules/modal/modal.module.ts
src/modules/select/select.module.ts

fix: Added missing ngModule imports to modal & select

---

demo/src/app/pages/modules/accordion/accordion.page.html

Spotted a dead link to one of the components. :)

docs(accordion): Fixed a dead link to ”Collapse” component

---

demo/src/app/pages/behaviors/localization/localization.page.ts
src/behaviors/localization/locales/index.ts
src/behaviors/localization/locales/ru.ts

feat(localization): Add Russian locale

---

demo/src/app/pages/behaviors/localization/localization.page.ts
src/behaviors/localization/locales/he.ts
src/behaviors/localization/locales/index.ts

feat(localization): Add Hebrew locale

---

src/modules/popup/classes/popup-controller.ts

fix(popup): Fixed TS 2.4.1 no properties in common error

---

src/modules/modal/components/modal.ts
src/modules/popup/components/popup.ts

fix(modal/popup): Autofocus now working in IE11

---

src/modules/select/classes/select-base.ts
src/modules/select/components/multi-select.ts
src/modules/select/components/select.ts

fix(select): Fixed various JS falsy errors

---

src/modules/popup/classes/popup-controller.ts

fix(popup): Stopped attaching component to application repeatedly

---

demo/src/app/pages/modules/checkbox/checkbox.page.ts
src/collections/index.ts
src/misc/index.ts
src/misc/util/helpers/util.ts
src/modules/checkbox/checkbox.module.ts
src/modules/checkbox/components/radio.ts
src/modules/checkbox/directives/radio-manager.ts
src/modules/checkbox/index.ts

feat(checkbox): Added radiobutton support for reactive forms

---

package-lock.json
package.json
src/misc/util/services/positioning.service.ts

fix(popper): Fixed error introduced by included popper type definitions

---

demo/src/app/pages/modules/modal/modal.page.ts
demo/src/index.html
src/modules/modal/classes/modal-config.ts

Fixes https://github.com/edcarroll/ng2-semantic-ui/issues/203
*NOTE*: to use those sizes you should use Semantic-UI v2.2.11

fix(modal): add support for mini and tiny sizes

---

demo/src/app/pages/modules/select/select.page.ts
package-lock.json
src/behaviors/localization/interfaces/select-values.ts
src/behaviors/localization/locales/de.ts
src/behaviors/localization/locales/en-GB.ts
src/behaviors/localization/locales/es.ts
src/behaviors/localization/locales/fr.ts
src/behaviors/localization/locales/he.ts
src/behaviors/localization/locales/it.ts
src/behaviors/localization/locales/pt.ts
src/behaviors/localization/locales/ru.ts
src/modules/select/components/multi-select.ts

Fixes #188 
*NOTE*: a new message template needs translations
@maksim-m, @ciaraward, @genuinefafa, @gotenxds, @fniwes

feat(select): add support for hiding labels in multi-select

---

demo/src/app/pages/collections/message/message.page.html
demo/src/app/pages/collections/message/message.page.ts
src/collections/message/components/message.ts

fix(message): Icon messages now style correctly

---

src/modules/modal/components/modal.ts

fix(modal): Move modal back to original container after dismiss

---

src/modules/dimmer/components/dimmer.ts
src/modules/modal/components/modal.ts

fix(modal): Fixed modal scroll context sometimes breaking

---

src/modules/popup/components/popup.ts

fix(popup): Mousedown no longer cancelled on internal elements

---

src/modules/datepicker/directives/datepicker.directive.ts
src/modules/popup/classes/popup-component-controller.ts
src/modules/popup/classes/popup-controller.ts
src/modules/popup/directives/popup.directive.ts

Closes #194 
Document click handler is now manually applied by the renderer.

fix(popup): Made document click handler only apply when popup is open

---

package-lock.json
package.json

chore(popup): Relaxed popper.js dependency

---

src/modules/popup/classes/popup-controller.ts

fix(popup): Fixed delay causing destroyed view errors

---

demo/src/app/pages/modules/popup/popup.page.ts

fix(popup): Fixed globals being overidden on popup demo page

---

src/behaviors/localization/locales/index.ts
src/behaviors/localization/locales/nl.ts

Added Dutch translations

---

demo/src/app/app.component.css

demo: Added momentum scrolling support

---

src/modules/datepicker/views/calendar-view.ts
src/modules/datepicker/views/date-view.ts
src/modules/datepicker/views/hour-view.ts
src/modules/datepicker/views/minute-view.ts
src/modules/datepicker/views/month-view.ts
src/modules/datepicker/views/year-view.ts
src/modules/dropdown/directives/dropdown-menu.ts
src/modules/modal/components/modal.ts
src/modules/popup/classes/popup-controller.ts
src/modules/search/components/search.ts
src/modules/select/classes/select-base.ts
src/modules/select/components/multi-select.ts
src/modules/select/components/select.ts

fix: Manually added all document listeners to avoid performance issues

---

src/behaviors/localization/locales/de.ts

Added missing german translations and improved existing translations.

feat(localization): Improved German translations

---

package.json

Fix for https://github.com/edcarroll/ng2-semantic-ui/issues/317

chore: Change typescript peer dependency to use a caret

---

src/modules/select/classes/select-base.ts

Fix issue with keyboard navigation not working on select

---

package-lock.json
package.json
src/modules/dropdown/directives/dropdown-menu.ts
src/modules/transition/directives/transition.ts
src/package.json

fix(dropdown): Parent element accessed before initialisation

---

src/modules/dropdown/directives/dropdown-menu.ts

Always verify if the root object actually exists. Used your repo on an enterprise app and this bug was driving me mad. Nice work, btw!!

Fix dropdown-menu/isOpen of undefined

---

src/misc/util/helpers/util.ts

fix(select): Fixed nested labelField and valueField error

---

demo/src/app/pages/modules/popup/popup.page.ts
src/modules/popup/classes/popup-config.ts
src/modules/popup/classes/popup-controller.ts
src/modules/popup/components/popup.ts
src/modules/popup/directives/popup.directive.ts

popup flowing + popup inline
