- components/dropdown/dropdown-menu.ts
This caused a "e.srcElement is undefined" error in Firefox
> Use e.target instead of IE's e.srcElement

- components/select/multi-select.ts
In my last pull request, I introduced an error, when resetting the selectedOptions array in the multi-select component. I set the selectedOptions to 'null', which generates the error message "Cannot read property 'length' of null".
This pull request sets the selectedOptions to an empty array, so the error will be fixed and the labels will disappear from the multi-select as intended.
> Set selectedoptions to empty array not null

- components/collapse/collapse.ts
- demo/src/app/pages/accordion/accordion.page.html
- demo/src/app/pages/collapse/collapse.page.html
- demo/src/app/pages/collapse/collapse.page.ts
- demo/src/polyfills.ts
- package.json
- rollup.config.js
This PR moves the `web-animations-js` polyfill back outside the library, so it must be manually imported by users when using either the collapse or accordion components.
Warnings & instructions have been added to the collapse & accordion docs, so that full browser support can be easily achieved.
This closes #91 and #92.
> v0.8.2 into master

- components/checkbox/checkbox.ts
- components/checkbox/radiobutton.ts
- components/dropdown/dropdown.service.ts
- components/dropdown/dropdown.ts
- components/modal/modal-config.ts
- components/modal/modal-controls.ts
- components/modal/modal.service.ts
- components/modal/modal.ts
- components/popup/popup-arrow.ts
- components/popup/popup.directive.ts
- components/popup/popup.ts
- components/search/search.service.ts
- components/search/search.ts
- components/select/multi-select.ts
- components/select/select-base.ts
- components/select/select.ts
- components/tabs/tabset.ts
- components/transition/transition-controller.ts
- components/transition/transition.ts
- components/util/util.ts
- demo/src/app/modals/alert.modal.ts
- demo/src/app/modals/confirm.modal.ts
- demo/src/app/pages/modal/modal.page.ts
- tsconfig.json
- tslint.json
Also banned use of `null` keyword for simplicity, as peppering code with both `null` and `undefined` isn't the best thing ever.
> refactor: Added support for strict null checks

- src/checkbox/checkbox.ts
- src/checkbox/radiobutton.ts
- src/dropdown/dropdown-menu.ts
- src/dropdown/dropdown.service.ts
- src/dropdown/dropdown.ts
- src/search/search.ts
- src/select/select-base.ts
Closes #128 
Adds support for tabbing between search, select & dropdown components. This means that they automatically open & close as they gain and lose focus.
Checkboxes now also gain focus (& focus styles) when clicked.
> fix(select): Improved keyboard support

- src/modules/modal/classes/modal-template.ts
This stops it from being erased by Typescript, so when people use it in decorators it still exists. Closes #171
> fix(modal): Changed ModalTemplate to be an abstract class

- src/behaviors/localization/locales/es.ts
weekdaysShort for Wednesday was "Mie" should be "Mié"
> Fix typo (acute missing)

- src/modules/select/components/select.ts
When `<sui-select>`  ngModel set to a `undefined` value, `<sui-select>` can not clear the selected value.
This fix for sometime we want to clear the selected value.
> fix(select): When sui-select ngModel set undefined, reset selectedOption

- src/modules/select/classes/select-base.ts
- src/modules/select/components/multi-select.ts
- src/modules/select/components/select-option.ts
- src/modules/select/components/select.ts
> fix(select): Manually run change detector when option updates

- src/modules/select/components/multi-select.ts
- src/modules/select/components/select.ts
> fix(select): Selected options now updated when options change

- src/modules/modal/components/modal.ts
- src/modules/popup/components/popup.ts
This fixes an issue that ***occasionally*** occurs with things like dropdowns & modals - autofocus causes an early close in the dropdown which causes a changed after checked error...
> fix(modal): Fixed aggressive autofocus sometimes causing errors

- src/modules/popup/classes/popup-controller.ts
> fix(popup): Fixed conflict with BrowserAnimationsModule

- demo/src/app/pages/modules/popup/popup.page.html
- demo/src/app/pages/modules/popup/popup.page.ts
- src/modules/popup/classes/popup-config.ts
- src/modules/popup/classes/popup-controller.ts
- src/modules/popup/classes/popup-template-controller.ts
- src/modules/popup/directives/popup.directive.ts
- src/modules/popup/index.ts
- src/modules/popup/public.ts
> feat(popup): Added template context support

- src/modules/popup/classes/popup-controller.ts
- src/modules/popup/components/popup.ts
The previous focus PR was causing some issues with how focus events are handled by the popup. This fixes those issues.
> fix(popup): Fixed focus events on popup

- src/behaviors/localization/locales/es.ts
- src/modules/datepicker/classes/calendar-mappings.ts
- src/modules/datepicker/views/date-view.ts
- src/modules/datepicker/views/hour-view.ts
- src/modules/datepicker/views/minute-view.ts
- src/modules/datepicker/views/month-view.ts
- Datepicker popup items now respect locale format
- Fixed a bug in zoom calendar mapping for datetime datepicker
- Fixed 'es' locale for consistency
(*) Partially addresses #164
> feat(datepicker) Popup now honors locale and pickerLocaleOverrides

- demo/src/app/pages/behaviors/localization/localization.page.ts
- src/behaviors/localization/interfaces/datepicker-values.ts
- src/behaviors/localization/locales/en-GB.ts
- src/behaviors/localization/locales/en-US.ts
- src/behaviors/localization/locales/he.ts
- src/behaviors/localization/locales/it.ts
- src/behaviors/localization/locales/ru.ts
- src/modules/datepicker/helpers/date-fns.ts
Original "HH:mm" (23:59) -> Now "hh:mm aa" (11:59 p.m.)
> en-GB and en-US locales now use 12 hour format

- demo/src/app/pages/modules/datepicker/datepicker.page.ts
- src/modules/datepicker/directives/datepicker.directive.ts
- src/modules/datepicker/services/calendar.service.ts
- New input (optional) that sets the intial date to display (null = today)
- Updated demo page
Partially addresses #165
> feat(datepicker) New input pickerInitialDate

- src/modules/modal/components/modal.ts
- src/modules/popup/classes/popup-controller.ts
- src/modules/popup/directives/popup.directive.ts
- src/modules/select/classes/select-base.ts
PR to address a couple of the issues that have cropped up from the changes made over the last few days.
> fix: Various minor bugfixes

- demo/src/index.html
- src/behaviors/localization/locales/en-AU.ts
- src/behaviors/localization/locales/en-GB.ts
- src/behaviors/localization/locales/en-US.ts
- src/behaviors/localization/locales/he.ts
- src/behaviors/localization/locales/it.ts
- src/modules/datepicker/components/calendar-view-title.ts
- src/modules/datepicker/components/datepicker.ts
- src/modules/datepicker/datepicker.module.ts
- src/modules/datepicker/index.ts
- src/modules/datepicker/views/date-view.ts
- src/modules/datepicker/views/hour-view.ts
- src/modules/datepicker/views/minute-view.ts
- src/modules/datepicker/views/month-view.ts
- src/modules/datepicker/views/year-view.ts
- src/modules/dropdown/directives/dropdown-menu.ts
- src/modules/popup/classes/popup-component-controller.ts
- src/modules/popup/classes/popup-controller.ts
- src/modules/popup/components/popup.ts
* Update US & GB locales to use uppercase meridian time
* Adds support for long locale strings in the calendar views (titles no longer overflow)
* Fix datepicker focusout & destroyed view issues
* Fix component popup duplication glitch (rapid open & close)
* Ensure component popup is destroyed when component is destroyed
* Fixed error on keyboard navigation of empty dropdown
* Update to Semantic UI 2.2.13 (in the demo)
> fix: Minor bugs

- src/collections/pagination/components/pagination.spec.ts
- src/collections/pagination/components/pagination.ts
Hey, Was having a problem with starting the pagination component on a different page number. 
This was because this.pageCount was set after page range checks. Meaning this line (137) always = 1. 
```js
const value:number = (Number.isInteger(newPage)) ? Math.min(Math.max(newPage, 1), this.pageCount) : 1;
```
> fix(pagination) Keep start page number

- package-lock.json
- package.json
- src/misc/util/services/positioning.service.ts
Fixes #355 
- Updated Popper.js to 1.14.0 in package.json
- Use exported Interfaces from Popper.js
> Fix popper namespace

- package-lock.json
- package.json
- src/modules/dropdown/directives/dropdown-menu.ts
- src/modules/transition/directives/transition.ts
- src/package.json
Fixes issue introduced by performance fixes that breaks the dropdown due to it attempting to access it's parent element before it's been assigned.
> fix(dropdown): Parent element accessed before initialisation
